# This is a basic workflow that is manually triggered

on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
         node-version: '16.x'
      - uses: microsoft/playwright-github-action@v1
      - name: Install Playwright Browsers  
        run: npx playwright install --with-deps
      - name: Install dependencies and run tests
        run: npm install && npx playwright test
